### ISSUE TITLE
Camera not saving pictures?

### ISSUE THREAD

**Issue by hahnjo** [derfelot/discussion#14]
The default Camera tries to save the taken pictures in `/storage/emulated/0/` which does not exist. This has worked with the June release.

@Micha-Btz @MSe1969 Can you confirm this issue? Do you have an idea? I probably won't find time to look into this until Wednesday or so...

**Comment by MSe1969** [comment]
Works fine with my device - no issues at all.
/storage/emulated/0 exists (and so does the /sdcard symlink pointing there)

**Comment by Micha-Btz** [comment]
I have no problems:

> shell@amami:/ $ ls -la /storage/emulated/                                                                                                                              
> lrwxrwxrwx root     root              2017-07-17 19:57 0 -> /mnt/shell/emulated/0
> lrwxrwxrwx root     root              1971-02-21 19:39 legacy -> /mnt/shell/emulated/0
> shell@amami:/ $ 
>
photos are saved without problems.

**Comment by hahnjo** [comment]
Hmm, did you flash my build or the microG-patched one? Maybe I'm missing some patch...

**Comment by hahnjo** [comment]
Very interesting: If you create a directory via MTP, apps are not allowed to create files in them! Sorry for the noise!
