### ISSUE TITLE
Github Organization f. cm-12.1-amami

### ISSUE THREAD

**Issue by MSe1969** [derfelot/discussion#20]
As discussed with @hahnjo, we should build an own organization in Github for our project.
This allows that all of us have admin rights and can clone repos etc.

We could then also implement the following improvements:
- a slight mod in 'build' to name the product output accordingly
- own build manifest (instead of an ever-growing local manifest)
- project git (f. 'repo init')

We need to first of all reach an agreement on **whether** to do it, what its **name** should be.
Proposed names right now: 'amami-cm12.1', 'cm-12.1-amami', 'lineage-12-amami', ...

@Micha-Btz , @derfelot , @hahnjo : Feedback welcome

Thanks & regards, M.

**Comment by hahnjo** [comment]
In favor of doing this. I don't really care for the name but IMO this is still based on CyanogenMod, not LineageOS...

**Comment by Micha-Btz** [comment]
makes sense. I also doesn't care about the name but i like short names.

The main question is how far is cm-14.1 for amami. There was much work done so maybe we can 
generally switch to cm-14.1. But I'm not up to date with this.

Also I have no time for the next 3 three weeks to help. But I will look at the mails.

**Comment by MSe1969** [comment]
Also not up to date with progress on cm-14.1 
But when considering the option for other releases, there should not be any cm12 in it.

What about "lamcr" (Lean AMami Custom ROM)? short, not too difficult to remember, not used yet on github and Google does not really indicate any common abbreviation or brand or anything...

**Comment by MSe1969** [comment]
... or simply "amami-rom" ?

**Comment by MSe1969** [comment]
@hahnjo @Micha-Btz @derfelot - Quick vote:
A. amami-rom
B. lamcr
C. cm12.1-amami
?

**Comment by Micha-Btz** [comment]
c :-)

Am 21. September 2017 09:01:26 MESZ schrieb MSe1969 <notifications@github.com>:
>@hahnjo @Micha-Btz @derfelot - Quick vote:
>A. amami-rom
>B. lamcr
>C. cm12.1-amami
>?

**Comment by hahnjo** [comment]
c 👍

**Comment by MSe1969** [comment]
Okay, C it is

**Comment by MSe1969** [comment]
dots are not allowed, so I made it **cm12-amami**

**Comment by hahnjo** [comment]
You can probably set a title, that's only for URL I suppose

**Comment by MSe1969** [comment]
Okay, have seen you accepted the invitation and I have made you "owners", too
So all of us (when @derfelot accepts, we have to do the same for his account) are full admins now.

**Comment by MSe1969** [comment]
So we can now continue to discuss and setup the new org there, so I will close this issue
I have forked this repo already.
