### ISSUE TITLE
Remove Tracking and Google dependencies from Trebuchet, LockClock and SetupWizard

### ISSUE THREAD

**Issue by MSe1969** [derfelot/discussion#8]
It is desirable to backport the LineageOS changes to remove Google Play dependencies and Tracking from the below system apps:

Trebuchet (launcher)
LockClock (clock & weather widget)
SetupWizard (initial setup)

To do so, the following commits need to be backported and the respective repositories need to be forked:
Trebuchet: https://review.lineageos.org/#/c/157952/
LockClock: https://review.lineageos.org/#/c/162231/
SetupWizard: https://review.lineageos.org/#/c/162218/
vendor/cmsdk: https://review.lineageos.org/#/c/161542/

I will temporarily fork the repositories into my area (MSe1969), after finalization, they will be forked into derfelot.

**Comment by Micha-Btz** [comment]
Great, would love to have this ones.
Maybe we should completely remove ambient-sdk like here
https://review.lineageos.org/#/c/144796/

**Comment by MSe1969** [comment]
Hi all, short status update:

1. Trebuchet and LockClock done, looks good so far.
@derfelot - please fork the following branches from my repo to here: 
MSe1969/cm_platform_sdk
MSe1969/android_packages_apps_LockClock
MSe1969/android_packages_apps_Trebuchet

They all only have the changes in the cm-12.1 branch and no test branch exists, but as those repo's come in 1st time, a test branch is not necessary; we will only point the local manifest in cm-12.1-test to it for the testing.

2. Starting to look at SetupWizard later today

3. @Micha-Btz : Before removing ambient, we would also need to clean out the messaging app, which of course would make sense, but that seems to be a more complicated thing to do... - will look into it.

**Comment by MSe1969** [comment]
@Micha-Btz - ambient is not part of cm-12.1

**Comment by Micha-Btz** [comment]
Ah, i have had a look at the source and nothing found :-)
Have done a build yesterday evening and no problems so far.

**Comment by MSe1969** [comment]
=> ready for shipment

**Comment by MSe1969** [comment]
Shipping the changes, so closing this issue now
