### ISSUE TITLE
Backport: Stats tracking reduction/elimination

### ISSUE THREAD

**Issue by MSe1969** [derfelot/discussion#9]
I think we also need to backport the below changes and need to fork LineageOS/android_packages_apps_Settings accordingly:

https://review.lineageos.org/#/c/154393
https://review.lineageos.org/#/c/154394
https://review.lineageos.org/#/c/154395
https://review.lineageos.org/#/c/155748/

**Comment by Micha-Btz** [comment]
Just let us do so.

**Comment by MSe1969** [comment]
Okay, done - test build is compiling... (will push my commits afterwards)

**Comment by MSe1969** [comment]
Okay, all done - looks good. I've also backported https://review.lineageos.org/#/c/154080/
Test build looks good, manifest updated.

What has been changed?
1. Rebrand: In the settings, all is now referred to as 'LineageOS' and not 'CyanogenMod' any longer
2. Data privacy policy now displayable from LOS site (cyngn.com anyhow dead link)
2. In 'CyanogenMod' times, there were in fact two stats-tracking jobs, as far as I can tell from looking at the code:
a. The 'community' one, which was pretty static (simply ROM Version and device), to which you could opt out
b. The 'Cyanogen Inc' one, which was always sent to cyngn.com, including - for their statistical purposes - the fact whether you had opted out or not ...
The Cyanogen Inc. one has been entirely eliminated and the community one is now sent to LOS (for those opting to do so - by default disabled)

=> ready for shipment

**Comment by MSe1969** [comment]
Shipping the changes, so closing this issue now
